# Generated by Django 4.0.2 on 2022-02-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('applying', models.TextField(max_length=255)),
                ('composition', models.TextField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_mail', models.CharField(max_length=255)),
                ('mention_text', models.TextField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_shop.product')),
            ],
        ),
    ]
