# Generated by Django 4.0.2 on 2022-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_shop', '0002_product_info_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentions',
            name='mention_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='applying',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='composition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='description',
            field=models.TextField(),
        ),
    ]
